-- Wild Oasis schema restored from backup (2025-02-17)

CREATE TABLE public.settings (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    min_booking_length smallint,
    max_booking_length smallint,
    max_guests_per_booking smallint,
    breakfast_price real
);

CREATE TABLE public.cabins (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    name text,
    max_capacity smallint,
    regular_price smallint,
    discount smallint,
    description text,
    image text
);

CREATE TABLE public.guests (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    full_name text,
    email text,
    nationality text,
    country_flag text,
    national_id text
);

CREATE TABLE public.bookings (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    num_nights smallint,
    num_guests smallint,
    cabin_price real,
    extras_price real,
    total_price real,
    status text,
    has_breakfast boolean,
    is_paid boolean,
    observations text,
    cabin_id bigint REFERENCES public.cabins(id) ON UPDATE CASCADE ON DELETE CASCADE,
    guest_id bigint REFERENCES public.guests(id) ON UPDATE CASCADE ON DELETE CASCADE
);

GRANT ALL ON TABLE public.settings TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.cabins TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.guests TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.bookings TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cabins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow to CRUD cabins" ON public.cabins TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow to CRUD guests" ON public.guests TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow to CRUD setting" ON public.bookings TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow to update a setting" ON public.settings FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable read access for all users" ON public.settings FOR SELECT TO authenticated USING (true);

-- Server-side Next.js app uses anon key
CREATE POLICY "Allow anon cabins" ON public.cabins FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon guests" ON public.guests FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon bookings" ON public.bookings FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon settings" ON public.settings FOR ALL TO anon USING (true) WITH CHECK (true);

INSERT INTO storage.buckets (id, name, public)
VALUES ('cabin_images', 'cabin_images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

CREATE POLICY "Public read cabin images"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'cabin_images');

CREATE POLICY "Service role manage cabin images"
ON storage.objects FOR ALL
TO service_role
USING (bucket_id = 'cabin_images')
WITH CHECK (bucket_id = 'cabin_images');
